package automacao.enuns;

public enum EnumLabel {

	USUARIO ("Usuário"),
	SENHA ("Senha"),
	LABEL ("label"),
	CONTINUAR ("Continuar"),
	CANCELAR ("Cancelar"),
	EXCLUIR ("Excluir"),
	ALTERAR ("Alterar"),
	DETALHAR("Detalhar"),
	CONFIRMAR ("Confirmar"),
	INCLUIR ("Incluir"),
	VOLTAR ("Voltar"),
	OK ("OK"),
	LOGIN ("Log In"),
	ANEXAR ("Anexar"),
	ACESSAR ("Acessar"),
	LIMPAR ("Limpar"),
	CONSULTAR ("Consultar"),
	PESQUISAR ("Pesquisar"),
	SELECIONAR ("Selecionar"),
	SAIR ("Sair"),
	FECHAR ("Fechar"),
	PAGINACAO_PROXIMO ("Próxima"),
	PAGINACAO_ULTIMO ("Última"),
	PAGINACAO_PRIMEIRO ("Primeira"),
	PAGINACAO_ANTERIOR ("Anterior"),
	ATIVO ("Ativo"),
	INATIVO ("Inativo"),
	INCLUSAO ("Inclusão"),
	ALTERACAO ("Alteração"),
	EXCLUSAO ("Exclusão"),
	COMBO ("Combo"),
	CHECK_BOX ("Checkbox"),
	CHECK_BOX_MARCA_CEDIDA ("Marca cedida"),
	LINK ("Link"),
	CAMPO ("Campo"),
	RADIO_BOX ("Radio box"),
	BOTAO ("Botão"),
	GRID ("Grid"),
	CABECALHO_GRID ("Cabeçalho da grid"),
	MSG_VALIDACAO ("Mensagem de validação"),
	MSG_EXCLUSAO ("Mensagem de exclusão"),
	TELA_INCLUIR ("Incluir"),
	TELA_ALTERAR ("Alterar"),
	TELA_DETALHAR ("Detalhar"),
	TELA_PESQUISAR ("Pesquisar"),
	TELA_PRINCIPAL ("Principal"),
	MENSAGEM ("mensagem"),
	ABA ("aba"),
	IMAGEM ("imagem"),
	COMBO_VALOR_PADRAO(":: SELECIONE ::"),
	
	// Cadastro de Estabelecimento
	COMBO_AREA_INTERESSE("Área de interesse"),
	COMBO_ATIVIDADE("Atividade"),
	COMBO_CLASSIFICACAO_CATEGORIA("Classificação/Categoria"),
	COMBO_CARACTERISTICA_ADICIONAL("Característica adicional"),
	COMBO_ESPECIE("Espécie"),
	COMBO_DENOMINACOES("Denominações"),
	COMBO_ANALISE("Análise"),
	COMBO_TIPO_ARQUIVO("Tipo Arquivo"),
	COMBO_TIPO_INSTALACAO(" Tipo de instalação"),
	SIM("Sim"),
	NAO("Não"),
	TIPO_ENDERECO("Tipo de endereço"),
	TIPO_EQUIPAMENTO("Tipo de equipamento"),
	LABORATORIO("Laboratório"),
	CEP("Cep"),
	LINK_NAO_SEI_CEP("Não sei o CEP"),
	INPUT_OUTRAS_ANALISES("Outras Análises"),
	LUPA_PESQUISAR("Lupa pesquisar CEP"),	
	LISTA_LOGRADOUROS("Lista de logradouros"),
	BAIRRO("Bairro"),
	NUMERO("Número"),
	TIPO_CONTATO("Tipo de contato"),
	DESCRICAO("Descrição"),
	NOME("Nome"),
	RADIO_REGISTRO_ANTERIOR("Registro anterior"),
	RADIO_CADASTRO_ANTERIOR ("Possui cadastro anterior"),
	RADIO_POSSUI_NUM_RENASEM("Possui Nº RENASEM? (Se sim, anexar cópia do certificado)"),
	RADIO_NATUREZA_FISICA ("Natureza Física"),
	RADIO_PRODUCAO_ESTABELECIMENTO ("Produção do estabelecimento"),
	RADIO_PROPRIA ("Própria"),
	RADIO_PROPRIO ("Próprio"),
	RADIO_EXCLUSIVA ("Exclusiva para terceiros"),
	RADIO_TERCEIRO ("Terceiro"),
	RADIO_TITULAR ("Titular"),
	RADIO_SUBSTITUTO ("Substituto"),
	RADIO_FINALIDADE_USO ("Finalidade de uso"),
	INPUT_NUM_REGISTRO_ANTERIOR("Nº do registro anterior"),
	INPUT_NUM_CADASTRO_ANTERIOR("N° do cadastro anterior"),
	INPUT_DATA_CONCESSAO_1_REGISTRO("Data da concessão do 1° registro"),
	INPUT_DATA_CONCESSAO_1_CADASTRO("Data da concessão do 1° cadastro"),
	INPUT_DATA_ULTIMA_RENOVACAO("Data da última renovação"),
	INPUT_NUM_RENASEM("Nº RENASEM"),
	INPUT_DATA_VENCIMENTO("Data de vencimento"),
	INPUT_DATA_VALIDADE_REGISTRO("Data de validade do registro"),	
	INPUT_DENOMINACAO_MATERIAL ("Denominação do material"),
	INPUT_NOME_NOVA_TECNICA ("Nome da nova técnica"),
	INPUT_TEOR_NUTRIENTES ("Teor de nutrientes"),
	INPUT_FORMA_QUIMICA ("Forma química do(s) nutriente(s) do minério"),
	INPUT_NUMERO_PORTARIA ("N° da portaria de concessão de lavra do minério"),
	CHECK_BOX_TECNICA_NAO_LOCALIZADA ("Técnica não localizada"),
	COMBO_TIPO_RESPONSAVEL("Tipo responsável"),
	COMBO_TIPO_PROFISSAO("Tipo profissão"),
	COMBO_TIPO_CONSELHO("Tipo conselho"),
	COMBO_NOME_PRODUTO("Nome do produto"),
	COMBO_MODO_APLICACAO ("Modo aplicação"),
	COMBO_UNIDADE("Unidade"),
	COMBO_DETERMINACAO ("Determinação"),
	COMBO_TECNICA_UTILIZADA ("Técnica utilizada"),
	COMBO_UF("Uf"),
	COMBO_MATERIA_PRIMA ("Matéria prima "),
	COMBO_NATUREZA_FISICA ("Natureza física"),
	INPUT_NUMERO_CONSELHO("Número do conselho"),	
	INPUT_CAPACIDADE_OPERACIONAL("Capacidade operacional-ano"),
	INPUT_NUMERO_CADASTRO ("Nº de cadastro"),
	INPUT_QTD_DETERMINACAO_MENSAL ("Qtde de determinaçõe mensal"),
	INPUT_NUMERO_SOLICITACAO_CADASTRO_LABORATORIO ("Nº da solicitação de cadastro laboratório"),
	INPUT_NUMERO_REG_NACIONAL("Número de registro nacional"),
	INPUT_LATITUDE("Latitude"),
	INPUT_LONGITUDE("Longitude"),	
	INPUT_NOME_MARCA ("Nome da marca utilizada pelo estabelecimento"),
	INPUT_NUMERO_CADASTRO_ANTERIOR ("N° do cadastro anterior"),
	INPUT_DT_CONCESSAO (" Data da concessão do 1° cadastro"),
	INPUT_CAPACIDADE_MENSAL ("Capacidade Mensal"),
	LUPA_COORDENADAS("Lupa pesquisar Coordenadas"),	
	NENHUM("Nenhum"),
	TODOS("Todos"),
	PRIMEIRO("Primeiro"),	
	MARCADO("marcado"),
	DESMARCADO("desmarcado"),
	ARQUIVO("Arquivo"),
	ENVIAR_SOLICITACAO("Enviar solicitação"),
	INDICADOR_DE_RESPONSABILIDADE("Indicador de responsabilidade"),
	SELECIONE (":: SELECIONE ::"),
	
	//*********** ANALISAR ESTABELECIMENTO ***********************************
	COMBO_TIPO_PENDENCIA("Tipo"),
	DESPACHO ("Despacho"),
	TIPO_DESPACHO ("Tipo despacho"),
	ESTABELECIMENTO("Estabelecimento"),
	CPF("Cpf"),
	NATUREZA_SOLICITACAO( "Natureza da solicitação" ),
	CPF_CNPJ("CPF/CNPJ"),
	NUM_SOLICITACAO("Número da solicitação"),
	PENDENCIA("Pendência"),
	TIPO("Tipo"),
	DATA_LIMITE_PENDENCIA("Data da pendência"),
	DATA_DESPACHO("Dt. despacho"),
	DATA_ANEXO("Data do anexo"),
	DATA_LIMITE_RESPOSTA("Data limite p/ resposta"),
	SITUACAO("Situação"),
	REGISTRO_ANTERIOR ("Registro anterior"),
	INPUT_DATA_LIMITE_RESP_PENDENCIAS ("Data limite para resposta das pendências"),
	NUM_REGISTRO("N° do registro"),
	NUM_REGISTRO_NACIONAL("N° do registro nacional"),
	PROFISSAO("Profissão"),
	CONSELHO("Conselho"),
	NUM_CONSELHO("N° do conselho"),
	NOME_RESPONSAVEL_TECNICO("Nome do responsável técnico"),
	TELEFONE("Telefone"),
	EMAIL("E-mail"),
	GERAR_DESPACHO ("Gerar despacho"),
	SELECIONAR_ATIVIDADE("Selecionar Atividade"),
	TIRAR_SELECAO_ATIVIDADE("Tirar Seleção de Atividade"),
	TIPO_LABORATORIO("Tipo de Laboratório"),
	LUPA_PESQUISAR_RENASEM("Lupa pesquisar RENASEM"),
	
	;

	private String valor;

	public String value(){
		return this.valor;
	}

	private EnumLabel(String valor){
		this.valor = valor;
	}
}
